exports.prefix = ",";
exports.server = 'sim.smogon.com';
exports.port = 8000;
exports.serverid = 'showdown';
exports.avatar = 'supernerd';
exports.nickName = "1v1 OM Bot";
exports.pass = 'uwutoppy';
exports.autoJoin = ['botdev', 'groupchat-1v1-1v1oms'];
exports.admin = ['PartMan', 'Pokesartoolcay'];
exports.alpha = [];
exports.beta = ['ryyjyywyy', 'TapiocaTopic'];
exports.gamma = []
exports.locked = [];
